name: CI Tests

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  ci-tests:
    name: Python Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install apt dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libmariadb3 libmariadb-dev python3-dev build-essential pkg-config
    - name: Install pip dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Patch fastapi-mail for Python 3.12
      run: |
        pip install --upgrade "fastapi-mail>=1.4.1"
    - name: Run pytest (CI only)
      env:
        ENV_MAIL_USERNAME: ${{ secrets.ENV_MAIL_USERNAME }}
        ENV_MAIL_PASSWORD: ${{ secrets.ENV_MAIL_PASSWORD }}
        ENV_SECRET_KEY: ${{ secrets.ENV_SECRET_KEY }}
      run: |
        cd webapi; pytest tests/test_ci.py -v
  snyk-scan:
      name: Snyk Security Scan
      runs-on: ubuntu-latest
      # needs: ci-tests

      steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install apt dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libmariadb3 libmariadb-dev python3-dev build-essential pkg-config
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Snyk Scan
        uses: snyk/actions/python@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test --json-file-output=snyk_report.json
      - name: Upload Snyk report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-report
          path: snyk_report.json
